import PDFDocument from 'pdfkit'

/* Everixa PDF design: ink header band with the framed italic wordmark, brass rule, ivory-on-white body. */
const INK = '#111b2b'
const INK2 = '#263648'
const MUTED = '#6d7f99'
const BRASS = '#9a7336'
const BRASS_L = '#d9bf91'
const LINE = '#e1e6ed'
const IVORY = '#faf7f1'

const money = (n) => Number(n ?? 0).toLocaleString('en-US', { style: 'currency', currency: 'USD' })
const dateLong = (d) => (d ? new Date(typeof d === 'string' && d.length === 10 ? `${d}T12:00:00` : d).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }) : '—')

function start(title, subtitle) {
  const doc = new PDFDocument({ size: 'A4', margin: 0, info: { Title: title, Author: 'Everixa Workforce', Creator: 'Everixa Workforce' }, bufferPages: true })
  const chunks = []
  doc.on('data', (c) => chunks.push(c))
  const done = new Promise((resolve) => doc.on('end', () => resolve(Buffer.concat(chunks))))

  // Header band with the framed wordmark: EVERIXA WORKFORCE (one line, one style)
  doc.rect(0, 0, 595, 112).fill(INK)
  doc.rect(0, 112, 595, 3).fill(BRASS)
  doc.lineWidth(1).strokeColor(IVORY).strokeOpacity(0.8).rect(48, 26, 236, 38).stroke().strokeOpacity(1)
  doc.fillColor(IVORY).font('Times-BoldItalic').fontSize(17).text('EVERIXA WORKFORCE', 48, 37, { width: 236, align: 'center', characterSpacing: 1.2 })
  doc.fillColor(BRASS_L).font('Helvetica-Bold').fontSize(8).text(String(subtitle || '').toUpperCase(), 300, 38, { width: 247, align: 'right', characterSpacing: 2 })
  doc.fillColor(IVORY).font('Times-Roman').fontSize(26).text(title, 48, 72, { width: 499 })
  doc.fillColor(INK)
  return { doc, done, y: 146 }
}

function footer(doc, note) {
  const range = doc.bufferedPageRange()
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(i)
    doc.moveTo(48, 790).lineTo(547, 790).lineWidth(0.5).strokeColor(LINE).stroke()
    doc.fillColor(MUTED).font('Helvetica').fontSize(7.5)
    doc.text('Everixa Workforce · Staffing & Recruitment since 2006 · 110 N Wacker Drive, Chicago, IL 60606 · (863) 243-3789', 48, 798, { width: 499, lineBreak: false })
    doc.text(note || 'Generated by the Everixa employee portal.', 48, 810, { width: 380, lineBreak: false })
    doc.text(`Page ${i + 1} of ${range.count}`, 447, 810, { width: 100, align: 'right', lineBreak: false })
  }
}

const eyebrow = (doc, text, x, y) => doc.fillColor(BRASS).font('Helvetica-Bold').fontSize(7.5).text(text.toUpperCase(), x, y, { characterSpacing: 1.8 })

function kv(doc, label, value, x, y, w = 150) {
  doc.fillColor(MUTED).font('Helvetica-Bold').fontSize(7).text(label.toUpperCase(), x, y, { width: w, characterSpacing: 1.2 })
  doc.fillColor(INK).font('Helvetica').fontSize(10.5).text(String(value ?? '—'), x, y + 12, { width: w })
}

function sectionTitle(doc, title, y) {
  doc.fillColor(INK).font('Times-Roman').fontSize(17).text(title, 48, y)
  doc.moveTo(48, y + 24).lineTo(547, y + 24).lineWidth(0.75).strokeColor(INK).stroke()
  return y + 34
}

function lineRows(doc, rows, y, { negative = false, total } = {}) {
  for (const [k, v] of rows) {
    doc.fillColor(INK2).font('Helvetica').fontSize(10).text(k, 48, y, { width: 340 })
    doc.fillColor(INK).font('Helvetica').fontSize(10).text(`${negative ? '−' : ''}${money(v)}`, 400, y, { width: 147, align: 'right' })
    doc.moveTo(48, y + 17).lineTo(547, y + 17).lineWidth(0.4).strokeColor(LINE).stroke()
    y += 24
  }
  if (total) {
    doc.fillColor(INK).font('Helvetica-Bold').fontSize(10.5).text(total[0], 48, y, { width: 340 })
    doc.text(`${negative ? '−' : ''}${money(total[1])}`, 400, y, { width: 147, align: 'right' })
    y += 28
  }
  return y
}

function finish({ doc, done }, note) {
  footer(doc, note)
  doc.end()
  return done
}

/* ── Pay statement ───────────────────────────────────────────── */
export function payStubPdf(user, stub) {
  const ctx = start('Earnings Statement', 'Pay statement')
  const { doc } = ctx
  let y = ctx.y
  eyebrow(doc, 'Employee', 48, y)
  kv(doc, 'Name', `${user.firstName} ${user.lastName}`, 48, y + 16, 200)
  kv(doc, 'Employee ID', user.employeeId, 260, y + 16, 120)
  kv(doc, 'Position', user.position ?? 'Team Member', 390, y + 16, 157)
  y += 66
  kv(doc, 'Pay date', dateLong(stub.payDate), 48, y, 200)
  kv(doc, 'Pay period', `${dateLong(stub.periodStart)} – ${dateLong(stub.periodEnd)}`, 260, y, 287)
  y += 56

  y = sectionTitle(doc, 'Earnings', y)
  const earn = [[`Regular · ${Number(stub.regular).toFixed(2)} h × ${money(stub.rate)}`, stub.regular * stub.rate]]
  if (stub.overtime) earn.push([`Overtime · ${Number(stub.overtime).toFixed(2)} h × ${money(stub.rate * 1.5)}`, stub.overtime * stub.rate * 1.5])
  if (stub.bonus) earn.push(['Bonus / adjustment', stub.bonus])
  y = lineRows(doc, earn, y, { total: ['Gross pay', stub.gross] })
  y = sectionTitle(doc, 'Taxes', y + 4)
  y = lineRows(doc, Object.entries(stub.taxes), y, { negative: true, total: ['Total taxes', stub.totalTaxes] })
  if (Object.keys(stub.deductions).length) {
    y = sectionTitle(doc, 'Deductions', y + 4)
    y = lineRows(doc, Object.entries(stub.deductions), y, { negative: true, total: ['Total deductions', stub.totalDeductions] })
  }

  doc.rect(48, y + 6, 499, 58).fill(INK)
  doc.fillColor(BRASS_L).font('Helvetica-Bold').fontSize(8).text('NET PAY', 66, y + 22, { characterSpacing: 2 })
  doc.fillColor(IVORY).font('Times-Roman').fontSize(28).text(money(stub.net), 300, y + 17, { width: 229, align: 'right' })
  return finish(ctx, 'This statement is an informational copy of your earnings.')
}

/* ── W-2 summary ─────────────────────────────────────────────── */
export function w2Pdf(user, year, t) {
  const ctx = start(`Wage & Tax Statement ${year}`, 'Form W-2 summary')
  const { doc } = ctx
  let y = ctx.y
  eyebrow(doc, 'Employee', 48, y)
  kv(doc, 'Name', `${user.firstName} ${user.lastName}`, 48, y + 16, 220)
  kv(doc, 'Employee ID', user.employeeId, 290, y + 16, 120)
  kv(doc, 'Tax year', String(year), 430, y + 16, 117)
  y += 66
  eyebrow(doc, 'Employer', 48, y)
  kv(doc, 'Name', 'Everixa Workforce LLC', 48, y + 16, 220)
  kv(doc, 'Address', '110 N Wacker Drive, Chicago, IL 60606', 290, y + 16, 257)
  y += 70

  y = sectionTitle(doc, 'Wages and withholding', y)
  const boxes = [
    ['1  Wages, tips, other compensation', t.wages], ['2  Federal income tax withheld', t.federal],
    ['3  Social Security wages', t.wages], ['4  Social Security tax withheld', t.socialSecurity],
    ['5  Medicare wages and tips', t.wages], ['6  Medicare tax withheld', t.medicare],
    ['16  State wages', t.wages], ['17  State income tax', t.state],
  ]
  for (let i = 0; i < boxes.length; i += 2) {
    for (let j = 0; j < 2; j++) {
      const [label, val] = boxes[i + j]
      const x = 48 + j * 254
      doc.lineWidth(0.6).strokeColor(LINE).rect(x, y, 245, 54).stroke()
      doc.fillColor(MUTED).font('Helvetica-Bold').fontSize(7).text(label.toUpperCase(), x + 10, y + 9, { width: 225, characterSpacing: 0.8 })
      doc.fillColor(INK).font('Times-Roman').fontSize(19).text(money(val), x + 10, y + 24, { width: 225 })
    }
    y += 62
  }
  doc.fillColor(MUTED).font('Helvetica').fontSize(8.5).text(`Based on ${t.periods} pay statement${t.periods === 1 ? '' : 's'} recorded for ${year}. This is an informational statement prepared by Everixa payroll; official IRS copies are provided by your payroll processor.`, 48, y + 12, { width: 499, lineGap: 2 })
  return finish(ctx, 'Informational copy — not an official IRS form.')
}

/* ── W-4 ─────────────────────────────────────────────────────── */
export function w4Pdf(user, w4) {
  const FILING = { single: 'Single or Married filing separately', married: 'Married filing jointly', head: 'Head of household' }
  const ctx = start('Withholding Certificate', 'Form W-4 summary')
  const { doc } = ctx
  let y = ctx.y
  eyebrow(doc, 'Employee', 48, y)
  kv(doc, 'Name', `${user.firstName} ${user.lastName}`, 48, y + 16, 220)
  kv(doc, 'Employee ID', user.employeeId, 290, y + 16, 120)
  kv(doc, 'Effective', dateLong(w4.approvedAt ?? w4.submittedAt), 430, y + 16, 117)
  y += 80
  y = sectionTitle(doc, 'Your elections', y)
  const rowsData = [
    ['Step 1(c) · Filing status', FILING[w4.filing] ?? w4.filing],
    ['Step 2 · Multiple jobs or working spouse', w4.multipleJobs === 'yes' ? 'Yes' : 'No'],
    ['Step 3 · Dependents credit', money(w4.dependents)],
    ['Step 4(a) · Other income', money(w4.otherIncome)],
    ['Step 4(b) · Deductions', money(w4.deductions)],
    ['Step 4(c) · Extra withholding per pay period', money(w4.extra)],
  ]
  for (const [k, v] of rowsData) {
    doc.fillColor(INK2).font('Helvetica').fontSize(10.5).text(k, 48, y, { width: 300 })
    doc.fillColor(INK).font('Helvetica-Bold').fontSize(10.5).text(v, 350, y, { width: 197, align: 'right' })
    doc.moveTo(48, y + 18).lineTo(547, y + 18).lineWidth(0.4).strokeColor(LINE).stroke()
    y += 28
  }
  doc.fillColor(MUTED).font('Helvetica').fontSize(8.5).text('This summary reflects the withholding elections approved by Everixa payroll. It is not tax advice.', 48, y + 14, { width: 499 })
  return finish(ctx, 'Informational copy — not an official IRS form.')
}

/* ── 1095-C summary ──────────────────────────────────────────── */
export function f1095Pdf(user, year, election) {
  const ctx = start(`Health Coverage ${year}`, 'Form 1095-C summary')
  const { doc } = ctx
  let y = ctx.y
  eyebrow(doc, 'Employee', 48, y)
  kv(doc, 'Name', `${user.firstName} ${user.lastName}`, 48, y + 16, 220)
  kv(doc, 'Employee ID', user.employeeId, 290, y + 16, 120)
  kv(doc, 'Tax year', String(year), 430, y + 16, 117)
  y += 80
  y = sectionTitle(doc, 'Offer of coverage', y)
  const rowsData = [
    ['Plan offered', 'Minimum essential coverage providing minimum value'],
    ['Plan elected', election?.medicalName ?? 'No medical plan elected'],
    ['Coverage level', election?.coverageLabel ?? '—'],
    ['Months covered', election && election.medical !== 'wv' ? '12' : '0'],
  ]
  for (const [k, v] of rowsData) {
    doc.fillColor(INK2).font('Helvetica').fontSize(10.5).text(k, 48, y, { width: 200 })
    doc.fillColor(INK).font('Helvetica-Bold').fontSize(10.5).text(v, 250, y, { width: 297, align: 'right' })
    doc.moveTo(48, y + 18).lineTo(547, y + 18).lineWidth(0.4).strokeColor(LINE).stroke()
    y += 28
  }
  doc.fillColor(MUTED).font('Helvetica').fontSize(8.5).text('Informational summary prepared by Everixa benefits administration.', 48, y + 14, { width: 499 })
  return finish(ctx, 'Informational copy — not an official IRS form.')
}

/* ── Shipment invoice ────────────────────────────────────────── */
export function invoicePdf(s) {
  const ctx = start('Invoice', `No. ${s.invoiceNumber}`)
  const { doc } = ctx
  let y = ctx.y
  kv(doc, 'Invoice date', dateLong(s.createdAt), 48, y, 160)
  kv(doc, 'Tracking number', s.tracking, 220, y, 170)
  kv(doc, 'Service', s.service || 'Everixa Courier', 400, y, 147)
  y += 56
  eyebrow(doc, 'Ship from', 48, y)
  doc.fillColor(INK).font('Helvetica').fontSize(10.5).text([s.from?.name, s.from?.address, `${s.from?.city ?? ''}${s.from?.state ? `, ${s.from.state}` : ''} ${s.from?.zip ?? ''}`.trim()].filter(Boolean).join('\n'), 48, y + 14, { width: 230, lineGap: 3 })
  eyebrow(doc, 'Ship to', 310, y)
  doc.fillColor(INK).font('Helvetica').fontSize(10.5).text([s.to?.name, s.to?.address, `${s.to?.city ?? ''}${s.to?.state ? `, ${s.to.state}` : ''} ${s.to?.zip ?? ''}`.trim()].filter(Boolean).join('\n'), 310, y + 14, { width: 237, lineGap: 3 })
  y += 100

  // Items table
  doc.rect(48, y, 499, 26).fill(INK)
  doc.fillColor(BRASS_L).font('Helvetica-Bold').fontSize(7.5)
  doc.text('DESCRIPTION', 60, y + 9, { characterSpacing: 1.4 })
  doc.text('QTY', 340, y + 9, { width: 40, align: 'right', characterSpacing: 1.4 })
  doc.text('UNIT PRICE', 385, y + 9, { width: 70, align: 'right', characterSpacing: 1.4 })
  doc.text('AMOUNT', 460, y + 9, { width: 77, align: 'right', characterSpacing: 1.4 })
  y += 26
  let subtotal = 0
  for (const it of s.items ?? []) {
    const amount = it.qty * it.unitPrice
    subtotal += amount
    doc.fillColor(INK).font('Helvetica').fontSize(10).text(it.description, 60, y + 9, { width: 270 })
    doc.text(String(it.qty), 340, y + 9, { width: 40, align: 'right' })
    doc.text(money(it.unitPrice), 385, y + 9, { width: 70, align: 'right' })
    doc.text(money(amount), 460, y + 9, { width: 77, align: 'right' })
    doc.moveTo(48, y + 30).lineTo(547, y + 30).lineWidth(0.4).strokeColor(LINE).stroke()
    y += 31
  }
  y += 14
  const totals = [['Subtotal', subtotal], ['Shipping & handling', s.shippingCost ?? 0]]
  for (const [k, v] of totals) {
    doc.fillColor(MUTED).font('Helvetica').fontSize(10).text(k, 330, y, { width: 100, align: 'right' })
    doc.fillColor(INK).text(money(v), 440, y, { width: 97, align: 'right' })
    y += 20
  }
  doc.rect(330, y + 4, 217, 44).fill(INK)
  doc.fillColor(BRASS_L).font('Helvetica-Bold').fontSize(8).text('TOTAL DUE', 344, y + 21, { characterSpacing: 2 })
  doc.fillColor(IVORY).font('Times-Roman').fontSize(20).text(money(subtotal + (s.shippingCost ?? 0)), 400, y + 15, { width: 133, align: 'right' })
  y += 64
  if (s.reference) {
    doc.fillColor(MUTED).font('Helvetica').fontSize(9).text(`Reference: ${s.reference}`, 48, y)
  }
  return finish(ctx, 'Thank you for choosing Everixa Workforce.')
}
