import { FileText, Download } from 'lucide-react'
import { documents } from '../../data/employeePortal'
import { getSession } from '../../lib/auth'

function downloadDocument(doc, employeeName) {
  const content =
`Everixa Workforce
--------------------------------
Document: ${doc.name}
Category: ${doc.category}
Date: ${doc.date}
Employee: ${employeeName}

This is a sample document generated by the Everixa Workforce
employee portal demo. In production this row would link to the
real file in employee storage.
`

  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `${doc.name.replace(/\s+/g, '-')}.txt`
  link.click()
  URL.revokeObjectURL(url)
}

export default function PortalDocuments() {
  const session = getSession()

  return (
    <div>
      <div className="mb-8">
        <p className="section-label mb-2">Documents</p>
        <h1 className="font-display text-3xl md:text-4xl font-bold text-forest-900">
          Your Documents & Pay Stubs
        </h1>
      </div>

      <div className="bg-white border border-forest-100 rounded-sm overflow-hidden">
        <div className="divide-y divide-forest-50">
          {documents.map((doc) => (
            <div key={doc.id} className="p-5 flex items-center gap-4 hover:bg-forest-50/50 transition-colors">
              <div className="w-10 h-10 bg-forest-50 border border-forest-100 rounded-sm flex items-center justify-center shrink-0">
                <FileText className="w-4 h-4 text-forest-600" />
              </div>
              <div className="flex-1 min-w-0">
                <p className="font-body text-sm font-semibold text-forest-900 truncate">{doc.name}</p>
                <p className="font-body text-xs text-forest-500">
                  {doc.category} · {doc.date} · {doc.size}
                </p>
              </div>
              <button
                onClick={() => downloadDocument(doc, session?.name)}
                className="inline-flex items-center gap-1.5 text-xs font-medium font-body
                           text-forest-600 hover:text-forest-800 transition-colors shrink-0
                           border border-forest-200 hover:border-forest-400 rounded-sm px-3 py-1.5"
              >
                <Download className="w-3.5 h-3.5" /> Download
              </button>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
